params_config:
  # general configs
  method: ["stagnn"] 

  agent_package: [100]
  ignore_keys: [['seed','index_runs','index_split']]
  save_model: [false]
  model_dir: ["exp/model/"]

  # configs for dataset
  exp_setting: ["setting_2"]
  dataset: ["cs"]
  sub_dataset: [""] 
  data_dir: ["../data/"]
  train_prop: [.6]
  valid_prop: [.2]
  rand_split: [true]

  # configs for model arch and training
  hidden_channels: [64]
  dropout: [0.6]
  lr: [0.001]
  weight_decay: [0.00005]
  epochs: [3000]
  eval_step: [1]
  log_freq: [1]
  patience: [200]
  metric: ["acc"]

  # configs for stagnn
  K: [3]
  pe: [true]
  pe_dim: [3]
  num_heads: [6]
  multi_concat: [false]
  ind_gamma: [true]
  gamma_softmax: [true]
  global_attn: [false]
 
  # configs for gnn baseline
  directed: [false]

  # configs for seed and number of runs
  seed: [3047]
  num_runs: [10]

sweep_config:
  method: "grid"
  metric:
    name: "metric/final"
    goal: "maximize"