params_config:
  # general configs
  method: ["pfgnn"] 

  agent_package: [100]
  ignore_keys: [['seed','index_runs','index_split']]
  save_model: [false]
  model_dir: ["exp/model/"]

  # configs for dataset
  exp_setting: ["nodeformer"]
  dataset: ["deezer-europe"]
  sub_dataset: [""] 
  data_dir: ["../data/"]
  train_prop: [.5]
  valid_prop: [.25]
  rand_split: [true]

  # configs for model arch and training
  hidden_channels: [64]
  dropout: [0.0,0.2,0.4,0.6,0.8]
  lr: [0.001,0.01]
  weight_decay: [0.0001,0.0005,0.001,0.005]
  epochs: [3000]
  eval_step: [1]
  log_freq: [1]
  patience: [200]
  metric: ["rocauc"]

  # configs for PFGNN
  K: [3,5,10]
  pe: [true]
  pe_dim: [3]
  num_heads: [1,2,4]
  multi_concat: [true,false]
  ind_gamma: [true]
  gamma_softmax: [true]
  aggr: ['random_walk_with_teleportation']

  # configs for gnn baseline
  directed: [false]

  # configs for seed and number of runs
  seed: [42]
  num_runs: [5]

sweep_config:
  method: "grid"
  metric:
    name: "metric/final"
    goal: "maximize"