params_config:
  # general configs
  method: ["pfgnn"] 

  agent_package: [100]
  ignore_keys: [['seed','index_runs','index_split']]
  save_model: [false]
  model_dir: ["exp/model/"]

  # configs for dataset
  exp_setting: ["setting_1"]
  dataset: ["deezer-europe"]
  sub_dataset: [""] 
  data_dir: ["../data/"]
  train_prop: [.5]
  valid_prop: [.25]
  rand_split: [true]

  # configs for model arch and training
  hidden_channels: [64]
  dropout: [0.0]
  lr: [0.01]
  weight_decay: [0.005]
  epochs: [3000]
  eval_step: [1]
  log_freq: [1]
  patience: [200]
  metric: ["rocauc"]

  # configs for PFGNN
  K: [3]
  pe: [true]
  pe_dim: [3]
  num_heads: [2]
  multi_concat: [true]
  ind_gamma: [true]
  gamma_softmax: [true]
  global_attn: [false]

  # configs for gnn baseline
  directed: [false]

  # configs for seed and number of runs
  seed: [42]
  num_runs: [5]

sweep_config:
  method: "grid"
  metric:
    name: "metric/final"
    goal: "maximize"